### ISSUE TITLE
Command failed, error in styntax

### ISSUE THREAD

**Issue by thebigmanaman** [josephillips85/gamepademu#5]
I have bought a pi zero w and trying to install this on it, but there is an error in the script : 
![Capture](https://user-images.githubusercontent.com/70802758/174293865-36f709c5-7a80-4c36-8ee2-81bc529a3540.PNG)

**Comment by thebigmanaman** [comment]
Full log
[log.txt](https://github.com/josephillips85/gamepademu/files/8927939/log.txt)

**Comment by thebigmanaman** [comment]
also, i try use the windows 10 fix, but windows continue to see unknown usb device
pi is fix green and guitar wo'nt connect

**Comment by josephillips85** [comment]
this look a broken dependency can you check at this moment?

**Comment by josephillips85** [comment]
The new commit fix any issue on the installer phase 
please use a bullseye lite image due a buster image is already deprecated.
